---
title: "script2"
output: html_document
---

```{r}
distance<-read.csv("dist2.csv")
closeteam<-read.csv("closesteam.csv")
distance<-distance[,-1]
head(distance)
```

```{r}
top<-data.frame(team=NA,nn1=NA,nn2=NA,nn3=NA,nn4=NA,nn5=NA,nn6=NA,nn7=NA,nn8=NA,nn9=NA,nn10=NA)
for (i in 1:nrow(distance)){
  top[i,]$team<-distance[i,]$index
  top[i,]$nn1<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[1]
  top[i,]$nn2<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[2]
  top[i,]$nn3<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[3]
  top[i,]$nn4<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[4]
  top[i,]$nn5<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[5]
  top[i,]$nn6<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[6]
  top[i,]$nn7<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[7]
  top[i,]$nn8<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[8]
  top[i,]$nn9<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[9]
  top[i,]$nn10<-colnames(sort(distance[i,2:ncol(distance)],descending =F))[10]
}
rownames(top)[2]<-2
```


```{r}
topnew<-top
topnew[,c(2:11)]<-sapply(top[,c(2:11)],function(x) substr(x,2,nchar(x)))
head(topnew)

write.csv(topnew,"topnew.csv")
```


```{r}
options(scipen=999)
topnew$team
```


```{r}
(sum(distance[,2:935] == 0) -935)/935
```






